CREATE OR REPLACE FUNCTION GET_TODO_LIST() RETURNS REFCURSOR AS $BODY$ DECLARE L_DATA REFCURSOR :='list';
BEGIN OPEN L_DATA FOR
SELECT d.ID,
	d.TASK_NAME,
	d.TASK_CONTEXT,
	d.CREATE_DATE,
	d.DEADLINE
FROM TODO_DATA d; RETURN L_DATA; END;
$BODY$ LANGUAGE PLPGSQL;


ALTER FUNCTION GET_EMP_LIST() OWNER TO POSTGRES;